env:
  global:
    - BRANCH=stable
    - QUIET=1
    - UML_DOCKERCOMPOSE=0
    - UML_FIG=0

sudo: true

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - echo "==> Building the main Docker images..."
  - ./run 'docker build  -t ansible  centos6      &&  docker run -i ansible > result-centos6'
  - ./run 'docker build  -t ansible  centos7      &&  docker run -i ansible > result-centos7'
  - ./run 'docker build  -t ansible  debian7      &&  docker run -i ansible > result-debian7'
  - ./run 'docker build  -t ansible  debian8      &&  docker run -i ansible > result-debian8'
  - ./run 'docker build  -t ansible  ubuntu12.04  &&  docker run -i ansible > result-ubuntu12.04'
  - ./run 'docker build  -t ansible  ubuntu14.04  &&  docker run -i ansible > result-ubuntu14.04'
  - ./run 'docker build  -t ansible  centos6-onbuild      &&  docker run -i ansible > result-centos6-onbuild'
  - ./run 'docker build  -t ansible  centos7-onbuild      &&  docker run -i ansible > result-centos7-onbuild'
  - ./run 'docker build  -t ansible  debian7-onbuild      &&  docker run -i ansible > result-debian7-onbuild'
  - ./run 'docker build  -t ansible  debian8-onbuild      &&  docker run -i ansible > result-debian8-onbuild'
  - ./run 'docker build  -t ansible  ubuntu12.04-onbuild  &&  docker run -i ansible > result-ubuntu12.04-onbuild'
  - ./run 'docker build  -t ansible  ubuntu14.04-onbuild  &&  docker run -i ansible > result-ubuntu14.04-onbuild'


  - echo "==> Validating the test results..."
  - grep '^ansible-playbook' result-centos6      ||  exit 1
  - grep '^ansible-playbook' result-centos7      ||  exit 1
  - grep '^ansible-playbook' result-debian7      ||  exit 1
  - grep '^ansible-playbook' result-debian8      ||  exit 1
  - grep '^ansible-playbook' result-ubuntu12.04  ||  exit 1
  - grep '^ansible-playbook' result-ubuntu14.04  ||  exit 1
  - grep '^ansible-playbook' result-centos6-onbuild      ||  exit 1
  - grep '^ansible-playbook' result-centos7-onbuild      ||  exit 1
  - grep '^ansible-playbook' result-debian7-onbuild      ||  exit 1
  - grep '^ansible-playbook' result-debian8-onbuild      ||  exit 1
  - grep '^ansible-playbook' result-ubuntu12.04-onbuild  ||  exit 1
  - grep '^ansible-playbook' result-ubuntu14.04-onbuild  ||  exit 1
